worker_processes auto;

events { worker_connections 4096; }

stream {
  # Where NGINX will listen for AMQP clients
  server {
    listen 5672;
    proxy_pass rabbitmq_amqp;
    proxy_connect_timeout 3s;
    proxy_timeout 1h;              # long-lived connections
    # optional: keepalive helps upstream reuse in some cases
    # proxy_socket_keepalive on;
  }

  upstream rabbitmq_amqp {
    least_conn;                     # or round_robin (default)
    server rabbit1:5672 max_fails=3 fail_timeout=10s;
    server rabbit2:5672 max_fails=3 fail_timeout=10s;
    server rabbit3:5672 max_fails=3 fail_timeout=10s;
  }
}

http {
  upstream rabbitmq_ui {
    least_conn;
    server rabbit1:15672;
    server rabbit2:15672;
    server rabbit3:15672;
  }

  server {
    listen 15672;

    location / {
      proxy_pass http://rabbitmq_ui;
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
  }
}