# rabbitmq.conf
cluster_formation.peer_discovery_backend = rabbit_peer_discovery_dns
cluster_formation.dns.hostname = rabbitmq
cluster_formation.node_cleanup.interval = 10
cluster_formation.node_cleanup.only_log_warning = true

# Optional: make it easier for clients to connect if you later use a load balancer
# loopback_users.guest = false
# listeners.tcp.default = 5672
# management.tcp.port = 15672

# docker exec -it rabbit1 rabbitmqctl cluster_status