services:
  rabbitmq:
    image: rabbitmq:4.1.1-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=myuser
      - RABBITMQ_DEFAULT_PASS=mypassword
    ports:
      - 5672:5672 # AMQP
      - 15672:15672 # Management UI
    volumes:
      - ./rabbitmq_data:/var/lib/rabbitmq